server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zx_db?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
